name: Reservar Presente

on:
  workflow_dispatch:
    inputs:
      id:
        required: true
        type: string
        
permissions:
  contents: write

jobs:

  reservar:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Atualizar JSON
        run: |
          node scripts/reservar.js ${{ github.event.inputs.id }}

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add src/assets/presentes.json

          git commit -m "Reserva presente ${{ github.event.inputs.id }}" || exit 0

          git push